# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8064d3d4aac93559506219f176e63063"
name = "Futuristek Storefront"
application_url = "https://admin.shopify.com"
embedded = false

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_inventory,unauthenticated_read_product_listings"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://futuristekstore.com/auth/callback" ]
